### ISSUE TITLE
Interpretation of Error Messages

### ISSUE THREAD

**Issue by ginsanity15** [tschoonj/xraylib#100]
Dear Developers of Xraylib,

I am trying to determine fluorescence cross section of high Z elements with the following code in C++:
`fluo_cs = CS_FluorLine(Z, KA_LINE, energy);`

For certain reason, I kept receiving messages as follow even though the output seems correct.
> Shell not available in function FluorYield
Line not available in function RadRate

May I know what does this mean? Is that the "meaningless errors" mentioned in wiki page? [https://github.com/tschoonj/xraylib/wiki/The-xraylib-API-list-of-all-functions#error-handling](url)

**Comment by tschoonj** [comment]
Yep these are indeed meaningless errors. Best is to call `SetErrorMessages (0)` at the start of your program.
