### ISSUE TITLE
running make on GitBash

### ISSUE THREAD

**Issue by linssab** [tschoonj/xraylib#114]
I've been trying to work around this issue for about 3 days now and with little success. I use GitBash on Windows. Make is not a default command and I had to work my way to install autotools on git, which worked fine. The problem as it seems is with the separators on Makefile. When running make command after having run `./configure` I get the error:

`Makefile:316: *** missing separator.  Stop.`

Idk if there is an easier way of installing xraylib to use its python bindings (python version 3.7) on GitBash, since the SDK installation doesn seem to work for me. Still get the no module found error when importing xraylib

**Comment by tschoonj** [comment]
I do not use GitBash on Windows and therefore do not support it.

I know that building and running xraylib (and its python bindings) works fine on MSYS2 though, so you may want to give that a try.

But if you really are just interested in using the python bindings, what I really recommend is using Anaconda: this would make your life a lot easier...

**Comment by linssab** [comment]
I guess I'll just go with anaconda then. Finally I surrender, been avoiding it for ages.
Thanks for the readily reply.
It is working now.

**Comment by tschoonj** [comment]
Glad to read you got it working now.

Good luck with Anaconda, I have grown to like it quite a bit myself.
