### ISSUE TITLE
Ignore Warning on Python

### ISSUE THREAD

**Issue by badruk** [tschoonj/xraylib#115]
When using the library I get this warning each time I try to delve into compounds, would it be possible to ignore it?

```
xraylib-parser: invalid character detected ,
CS_Total_CP: CompoundParser failed. Trying NIST compound database.
```

A Warning would be useful when the utility fails at finding a match: if it does in fact it just returns a 0 instead of a warning/error

**Comment by tschoonj** [comment]
Hi @badruk 

This is already fixed in master, and will be included in the next release.
For now, I recommend you just disable all warnings:

```python
xraylib.SetErrorMessages(0)
```

**Comment by tschoonj** [comment]
Closing, let me know if you have any other questions.
