### ISSUE TITLE
Energy range of cross sections: Missing documentation (and request for extension)

### ISSUE THREAD

**Issue by llohse** [tschoonj/xraylib#117]
I cannot find which for which energies the various cross sections are available. 
There does not seem to be a range check in the code. The data (I checked various PI cross sections) seems to end somewhere around 1 MeV and is simply repeated afterwards.
Kissel et al. provide PE cross sections well into the GeV range.

a) It would be nice to have some documentation for which energies the cross sections are available.

b) Would it be possible to include PI cross sections for higher energies as provided by Kissel?

**Comment by tschoonj** [comment]
Hi @llohse,

I will add some documentation about the energy ranges when I make the next release.

The Kissel database [files](https://github.com/tschoonj/xraylib/tree/master/data/kissel) I have go only up to 300 keV. If you have files that exceed this range please point me to them and I will have a look.

I will open a PR soon where I will introduce range checks to avoid the pointless repeating.

**Comment by tschoonj** [comment]
For the range checks: see #122 

It turns out I actually have the RTAB files with x suffix. Will investigate

**Comment by tschoonj** [comment]
The extended range files only cover the total PE cross sections, not the partial PE cross sections. In fact I don't even use the Kissel total PE cross sections in xraylib, and rely on the sum of the partial ones instead for CS_Photo_Total, as I apply a small correction to ensure the edge energies match with the ones returned by EdgeEnergy.

So sorry, but nothing I can do here I'm afraid...
