### ISSUE TITLE
Add google analytics tracking to Python and Java bindings

### ISSUE THREAD

**Issue by tschoonj** [tschoonj/xraylib#143]
Events will get sent once when the modules are loaded, and this will happen in a separate thread that will terminate afterwards.

**Comment by kalvdans** [comment]
Why? No one likes being tracked.

**Comment by tschoonj** [comment]
I like having a rough idea of how many people use my software and where they are from (approximately): this gives me some justification and the necessary drive to continue working on it and making new releases, especially since I do this mostly during weekends and holidays, as I am no longer involved with X-ray physics professionally.

I will consider adding an opt-out flag to avoid tracking, using an environment variable or so.

**Comment by tschoonj** [comment]
Google Analytics support was removed in #235, as Google removed the Universal Analytics some time ago, and any events sent were no longer being processed.
