### ISSUE TITLE
Question about KL1_LINE

### ISSUE THREAD

**Issue by yandaikang** [tschoonj/xraylib#19]
Hello,

I have a question about KL1_LINE: according to transition selection rule, K-->L1, K-->M1, K-->N1 transitions are forbidden, which however are listed in the "X-ray fluorescence line macros". Also the corresponding energies could be given calling the "LineEnergy" function.

I am thinking if this fluorescence database is directly deviated from the absorption energies, by subtracting different energy levels, without considering whether the transition would really happen...?

Thanks!

**Comment by tschoonj** [comment]
Hi

You are indeed correct: the _LINE macros correspond to all transitions based on the differences of two edge energies. Although cases like K &rarr; L1 are typically called forbidden transitions that doesn't mean that they are really impossible, just that they have a very, very low probability. Try for example `RadRate(82, L1M1_LINE)` and you will not get zero...
