### ISSUE TITLE
Cross-compilation issue with prdata

### ISSUE THREAD

**Issue by ttmms** [tschoonj/xraylib#202]
I'm cross-compiling to ARM64 with yocto/bitbake using autotools, and running into issue with prdata. As I understood, it is an intermediate helper tool to generate source files during the build. So it should not be cross-compiled because it then leads to exec format error when the build continues and tries to run ARM64 prdata binary on x86 host. Do you have any suggestions how to fix configure/makefile to not cross-compile this specific binary?

Thanks!

**Comment by tschoonj** [comment]
Hi,

You will need to use `meson`/`ninja` for that. More information can be found [here](https://mesonbuild.com/Cross-compilation.html).

**Comment by ttmms** [comment]
Alright, I suspected something like that! Unfortunately the required meson version is too high for my BSP, so I will have to find some hack in the meantime. Is meson >= 0.56.0 a hard requirement?

**Comment by tschoonj** [comment]
Probably, but you feel free to try with an older version. Can't you install a newer version of meson during the build? meson 0.56.0 was released in October 2020, so it's not exactly recent.
