### ISSUE TITLE
EdgeEnergy shell is invalid

### ISSUE THREAD

**Issue by bbazi** [tschoonj/xraylib#215]
Hi Tom,

When calculating the absorption edge energies for specific elements I got an error for Z=26 (Fe), I am going through all the shells as indicated in the xmimsimdata file.
Fe should contain 10 shells but when I call xraylib.EdgeEnergy(26, 9) for the last shell, the error says this last shell is invalid.
Do you perhaps see what's going on?

Cheers, Benjamin

![edgeenergy error](https://user-images.githubusercontent.com/82967994/204868740-6dc298e9-5352-4a2f-b10c-73487136e694.png)

**Comment by tschoonj** [comment]
This is because there are no edge energies available for Fe's N1 shell, even though it is occupied. There is Compton profile data available for that shell though, which is reflected in the XMI-MSIM data file.

**Comment by bbazi** [comment]
Thanks for the answer.
Best, Benjamin
