### ISSUE TITLE
Repository for Win installer can't be reached

### ISSUE THREAD

**Issue by LStarM** [tschoonj/xraylib#220]
Hello, I am trying to download the installer for Win OS but the repository can't be currently reached. Is it a temporary problem? How can I download it? Can you provide a direct link?

Thanks!
L.

**Comment by tschoonj** [comment]
Please use the [Github Releases](https://github.com/tschoonj/xraylib/releases) section now for Downloads.

**Comment by LStarM** [comment]
Thanks! I suggest updating the installation instructions.
