### ISSUE TITLE
Version in PyPI

### ISSUE THREAD

**Issue by ptim0626** [tschoonj/xraylib#238]
Thanks for the package.

I have recently tried to pip-install xraylib from PyPI (https://pypi.org/project/xraylib), but it doesn't have versions that support Python 3.11 and 3.12. I can see that it supports Python 3.11 and 3.12 in conda-forge (https://anaconda.org/conda-forge/xraylib). 

Does xraylib support installation from PyPI? Thank you

**Comment by tschoonj** [comment]
Hi Timothy, the xraylib wheels found on PyPI were not added by myself, but by the ESRF.

@srio can you help Tim out with this?

**Comment by ptim0626** [comment]
Just to check if there is any update on this? Thank you.

**Comment by srio** [comment]
Hello, and sorry for the late answer. Yes, we created the pypi wheels at ESRF. I'm looking to create the 3.11 and 3.12 ones, so I ask for a bit more patience (a few days hopefully...).

**Comment by ptim0626** [comment]
Hi @srio, much appreciate for the help!

**Comment by tschoonj** [comment]
I am not necessarily against publishing wheels through CI to PyPI, but the build backend I am using, [mesonpep517](https://pypi.org/project/mesonpep517), is not seeing further development, and lacks support for Windows.

I think that the backend needs to switch to [meson-python](https://github.com/mesonbuild/meson-python) instead, which is part of the meson project, and is actively developed.

Would you be willing to take a look at this?

**Comment by t20100** [comment]
I unfortunately have no experience with meson, but some of my colleagues do, I'll check with them.
If we can propose something, that will not be before this autumn..

**Comment by tschoonj** [comment]
I will try and do it myself then. I expect the changes will be limited to `pyproject.toml`

**Comment by tschoonj** [comment]
I just released version 4.1.5, and wheels were published to PyPI for Python version 3.8 to 3.13.

**Comment by t20100** [comment]
Many thanks!
