### ISSUE TITLE
pip install xraylib?

### ISSUE THREAD

**Issue by chrisvam** [tschoonj/xraylib#25]
Hi,

A number of us at SLAC/Stanford and Brookhaven are hoping to use a portable python package "scikit-xray" for algorithms.  xraylib is a dependency of that package.  scikit-xray has an anaconda-based installation that automatically installs xraylib, but anaconda brings in a significant number of other packages that conflict with software at our lab (and presumably the same problem would occur at other labs).  So we're looking into the possibility of using python's "pip install" to install scikit-xray, which doesn't bring in unneeded packages.  That works for scikit-xray, and its dependencies, except for xraylib, since you use configure/make.

My question: do you have thoughts on the possibility of a "pip install" installation for xraylib?  Perhaps I could try to do it (although I'm not sure yet how big a job it is).

Thought it wouldn't hurt to ask, and thanks for any thoughts,

chris

**Comment by tschoonj** [comment]
Hi Chris,

You're not the first one to approach me with this question :-)

Python is not a language I commonly use and unfortunately I know next to nothing about pip.
I would gladly help you out in any way I can, but I recommend you reach out to someone who is experienced at creating pip packages.

Best,

Tom

**Comment by danielballan** [comment]
In case anyone else is interested in this topic:

As discussed with @chrisvam over at scikit-xray/scikit-xray#337, conda (from the scientific Python community) is better tool for installing packages that contain non-Python code. At Brookhaven National Lab, we are building conda packages for xraylib and others. We have an OSX binary now; Windows binaries may be coming. See https://anaconda.org/danielballan/xraylib

**Comment by tschoonj** [comment]
Nice! I am sure this will benefit a lot of people.

Do you have any plans of creating a scikit-xray Homebrew formula for Mac OS X users (like myself)? I would like to give it a try myself.

**Comment by tschoonj** [comment]
Now that there are packages on conda-forge for all three major platforms, I consider this issue closed.

Given the difficulties involved, I have no plans to make a pip package, and that is unlikely to change.
