### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [tschoonj/xraylib#26]
I would like to point out that identifiers like "[`_XRAYLIB_H`](https://github.com/tschoonj/xraylib/blob/0389e72b456277be80d187c74c4f0dc075d3e24e/include/xraylib.h#L15)" and "[`_XRAYLIB_PARSER_H`](https://github.com/tschoonj/xraylib/blob/8f67269680458a36f7acd24c08c833daadc855ff/include/xraylib-parser.h#L16)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by tschoonj** [comment]
Sure, will put it on my to-do list. 

Thanks for reporting this

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/tschoonj/xraylib/commit/a1896de9a4f84c1371553679506cee95bc2ef93c#diff-4c8331b5d7fdc2a85c6c74d64674cd5bL16 "Deletion of a few underscores").
