### ISSUE TITLE
Unable to locate libxr17 and libxr17-dev packages 

### ISSUE THREAD

**Issue by saybr00k** [tschoonj/xraylib#28]
Hello, I'm trying to install xraylib on ubuntu 14.04. I executed:

curl http://lvserver.ugent.be/apt/xmi.packages.key | sudo apt-key add -

then used: sudo gedit /etc/apt/sources.list

which opened the text file where I entered:

deb [arch=amd64] http://lvserver.ugent.be/apt/ubuntu trusty stable
deb-src http://lvserver.ugent.be/apt/ubuntu trusty stable

and then saved the file.  After this I executed: sudo apt-get update

followed by: sudo apt-get install libxrl7 xraylib libxrl7-dev libxrlf03-7 libxrl-perl

at which point I get the error messages:
E: Unable to locate package libxr17
E: Unable to locate package libxr17-dev

Any help on figuring out why it can't seem to locate these packages would be amazing. One thing that does come up when I execute "sudo gedit /etc/apt/sources.list" is:
(gedit:4568)" IBUS-WARNING **: The owner of /home/saybrook/.config/ibus/bus is not root!

I'm not sure if this makes any difference. Thanks in advance for any help!

**Comment by tschoonj** [comment]
I think you made a typo somewhere. The error message says `libxr17`, which should be `libxrl7` (`1` vs `l`). Can you check if your sudo apt-get command corresponds exactly to what you wrote here?

**Comment by saybr00k** [comment]
Thank you for the quick response. I actually tried it many times and perhaps that was the issue(I'm not sure how to type the second 'number one' you wrote.  However, I tried 'sudo apt-get' without the xr17's and it prompted me to install them automatically which I did and everything seems to work now.

**Comment by tschoonj** [comment]
It's not a one: it's an `l`, the twelfth letter of the alphabet in lower case :smile:

**Comment by saybr00k** [comment]
Hah I thought it might be but then I couldn't reproduce it in the chat box here or the terminal XD. Thanks for your help at any rate

**Comment by tschoonj** [comment]
You're welcome. Let me know if you need help with using xraylib.

Tom
