### ISSUE TITLE
function signatures in xrayfunc.txt are incorrect (outdated)

### ISSUE THREAD

**Issue by bwharris1967** [tschoonj/xraylib#29]
function signatures in doc/xrayfunc.txt don't match those in xraylib.h

**Comment by tschoonj** [comment]
Thanks for bringing this up. It looks like doc/xrayhelp.txt suffers from the same problem.

**Comment by tschoonj** [comment]
I think this fixes things. Let me know if something else is wrong.

Many thanks again!
