### ISSUE TITLE
How to get the list of crystals available in xraylib?

### ISSUE THREAD

**Issue by srio** [tschoonj/xraylib#30]
From the examples, I should get it with 
```
crystals = xraylib.Crystal_GetCrystalsList()
```

but this function does not exist in my xraylib:

```
>>> import xraylib
>>> cryst = xraylib.Crystal_GetCrystal("Muscovite")
>>> xraylib.Bragg_angle (cryst, 10.0, 3, 3, 1)
0.431907830589977
>>> crystals = xraylib.Crystal_GetCrystalsList()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Crystal_GetCrystalsList'
>>> 

```

**Comment by tschoonj** [comment]
Hi Manolo,

I added this function only last week to the API. If you want to use it, you will need to clone and use the master branch to build a release with this function. 

Or, you could wait a couple of weeks until I release xraylib 3.2.0 :smile:

**Comment by srio** [comment]
Thanks a lot, Tom.

Just a last thing: could you remind me how to create the "configure" script not present in the git?

Thanks in advance, 

Manolo

**Comment by tschoonj** [comment]
autoreconf -i

On 22 Jan 2016, at 00:04, Manuel Sanchez del Rio <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks a lot, Tom.

Just a last thing: could you remind me how to create the "configure" script not present in the git?

Thanks in advance,

Manolo

�
Reply to this email directly or view it on GitHub<https://github.com/tschoonj/xraylib/issues/30#issuecomment-173666951>.

-- 
This e-mail and any attachments may contain confidential, copyright and or privileged material, and are for the use of the intended addressee only. If you are not the intended addressee or an authorised recipient of the addressee please notify us of receipt by returning the e-mail and do not use, copy, retain, distribute or disclose the information in or attached to the e-mail.
Any opinions expressed within this e-mail are those of the individual and not necessarily of Diamond Light Source Ltd. 
Diamond Light Source Ltd. cannot guarantee that this e-mail or any attachments are free from viruses and we cannot accept liability for any damage which you may sustain as a result of software viruses which may be transmitted in or with the message.
Diamond Light Source Limited (company no. 4375679). Registered in England and Wales with its registered office at Diamond House, Harwell Science and Innovation Campus, Didcot, Oxfordshire, OX11 0DE, United Kingdom
