### ISSUE TITLE
Windows installer kills path

### ISSUE THREAD

**Issue by adler-j** [tschoonj/xraylib#31]
It seems the current windows installer actually removes the PATH and sets it to `PATH=C:\Program Files (x86)\xraylib\Bin`. This is, for obvious reasons, not very good.

**Comment by tschoonj** [comment]
This is very surprising: that installer has been out for 18 months now and you are the first one bringing this up. I have tested this myself many times and have never encountered this. There is also no code in the installer script that could do this. 

Could you give me some more information?

I assume you are referring to the 3.1.0 installer? 32-bit or 64-bit? What version of Windows are you running?

Before installing, was there already an older version of xraylib installed?

Was your path variable already very long before you installed xraylib?

Thanks,

Tom

**Comment by adler-j** [comment]
> This is very surprising: that installer has been out for 18 months now and you are the first one bringing this up. I have tested this myself many times and have never encountered this. There is also no code in the installer script that could do this.

> Could you give me some more information?

Sure will do

> I assume you are referring to the 3.1.0 installer? 32-bit or 64-bit? What version of Windows are you running?

This is where I admit that I clicked the 2.16 installer by misstake, regardless it holds for both the 2.16 and the 2.16-cli installers (I tried). They are both 32-bit. I am running 64-bit. No errors during installation.

> Before installing, was there already an older version of xraylib installed?

No.

> Was your path variable already very long before you installed xraylib?

Quite long, yes, but not too long (I can append xraylib once i have installed without hitting the "roof".

I'll try the 3.1 installer now.

**Comment by tschoonj** [comment]
Ok, I understand the problem now. The old installers used NSIS instead of InnoSetup, and these NSIS installers were (are) notorious for chopping off very long environment variable values (1 kB by default) when appending to them. 

Fortunately the InnoSetup installers do not display this problem...

Sorry about this! Hope you could recover its contents!

**Comment by adler-j** [comment]
Ok great, it does indeed seem like the new one works fine!

If anyone else finds this issue and has this problem, this solves it:

http://stackoverflow.com/questions/7956365/need-to-recover-older-path-setting
