### ISSUE TITLE
Unit in x-ray fluorescence cross section

### ISSUE THREAD

**Issue by licode** [tschoonj/xraylib#34]
We often use cm2/g for the unit of x-ray fluorescence cross section. However, barn is also very popular for cross sections. Can I output fluorescence cross section in barn in xraylib? Thanks!

**Comment by licode** [comment]
I double checked the functions again. I think I just need to change xraylib.CS_FluorLine_Kissel to xraylib.CSb_FluorLine_Kissel.

**Comment by tschoonj** [comment]
Yep that is correct indeed.
