### ISSUE TITLE
Cannot get xraylib version from python

### ISSUE THREAD

**Issue by adler-j** [tschoonj/xraylib#37]
When installing xraylib from `apt-get` there is no `xraylib.__version__`, as is standard for python. Due to this I cannot check what version I have running locally.

**Comment by tschoonj** [comment]
You're right of course...

Ideally, the python files should be written to an xraylib folder in `site-packages`, along with an appropriate `__init__.py` and `version.py` file... 

I will look into it at some point, but if you have the time to fix this yourself and open a PR, I would be grateful :smile: 

Thanks for the other PR btw, I will merge it in.
