### ISSUE TITLE
Anomalies in f' and f'' data

### ISSUE THREAD

**Issue by mdw771** [tschoonj/xraylib#46]
Hi,

While trying to plot the values of anomalous scattering factors f' and f'' in the energy range from 10 eV to 30 keV, I noticed some local instabilities in the output data of functions `Fi` and `Fii` (please refer to attached graphs). These anomalies fluctuate by several orders of magnitudes, but the overall shape of the curve agrees well with the Henke data. 

For example, 
`Fi(14, 105.030000e-3)`
returns -896.729846725145, while Henke data for this energy is -2.04570.

I wonder this issue is due to the inherent anomalies in Kissel data?

Thanks,
Ming
[henke_kissel_comparison.pdf](https://github.com/tschoonj/xraylib/files/776066/henke_kissel_comparison.pdf)

**Comment by tschoonj** [comment]
Closed in #55
