### ISSUE TITLE
add xraylib into python path

### ISSUE THREAD

**Issue by licode** [tschoonj/xraylib#49]
I installed xraylib in my windows 10 (64 bit) system following online doc https://github.com/tschoonj/xraylib/wiki/Installation-instructions#windows-command-line-utility.

When I type xraylib in command, it works. However, it doesn't work when "import xraylib" in python. Any idea on this? Thanks!

**Comment by tschoonj** [comment]
The xraylib command line utility for Windows really includes just that: an executable generated using py2exe, with no (easy) way of accessing the underlying Python interpreter and/or xraylib module.

For that you will need to install the SDK, which can be installed alongside the command-line utility.

You may be interested to know that I am working on creating conda-forge xraylib packages for Windows [here](https://github.com/conda-forge/xraylib-feedstock/pull/5). They are currently working, but I want to clean up what goes into the tarball a bit better before merging it in.

**Comment by licode** [comment]
thanks! looking forward to the conda-forge version.

**Comment by tschoonj** [comment]
Available in conda-forge now.

**Comment by licode** [comment]
awesome! thanks a lot.
