### ISSUE TITLE
Questions on fluorescence crosssection

### ISSUE THREAD

**Issue by licode** [tschoonj/xraylib#50]
I can get x-ray fluorescence cross section from either command line or online table http://ftp.esrf.eu/pub/scisoft/xraylib/xraylib_tables_v2.3.pdf.

However, I find the results are not the same for some elements. Take Ti as an example, I run the command line as 
```
In [17]: xraylib.CSb_FluorLine_Kissel(22,xraylib.KA1_LINE,8)
Out[17]: 1832.0522750085834
``` 

From page 40 in the table, I can get Ti KA1 line at 8KeV as two values (1.71e+03 1.79e+03). So the value from command line is larger than the values in the table. I thus got the following 2 questions.

1. Can you please recommend which value I should use? Why are there two values in the table, from different models?

2. I also see from the table that the second column shows values for Ka2,1. I assume that means sum of Ka1 and Ka2. Just double check.

Thanks!

**Comment by tschoonj** [comment]
The first page of the pdf states that it was generated in November 2003. You may be surprised to hear that there have been a couple of changes to xraylib in the meantime 😄 

Please do not use that pdf. Rely only on the values generated by the last stable release.

**Comment by licode** [comment]
got it. thanks.
