### ISSUE TITLE
python3 files missing in python-libxrl7_3.3.0-1 deb packages

### ISSUE THREAD

**Issue by EricLandstrom** [tschoonj/xraylib#74]
The deb package is missing the files compared to 3.2.0:
/usr/lib/python3/dist-packages/xraylib_np.so                                                                                                                                                                                                      
/usr/lib/python3/dist-packages/_xraylib.so

**Comment by tschoonj** [comment]
Hi Eric, 

Which ubuntu/debian flavour are you using?

Thanks,

Tom

**Comment by EricLandstrom** [comment]
I'm on ubuntu xenial using python3 and xraylib-3.2.0. But that version is not longer available in your repo and looking in the package contents for 3.3.0 for both xenial and bionic, the compiled files are missing.

**Comment by tschoonj** [comment]
@EricLandstrom Could you confirm that the new packages work so I can close this issue?

Thanks!

**Comment by EricLandstrom** [comment]
@tschoonj sorry for the late reply, but the new packages work.

**Comment by tschoonj** [comment]
Thanks!
