### ISSUE TITLE
How to edit or add crystal structures in the crystal list for OASYS?

### ISSUE THREAD

**Issue by gwax09** [tschoonj/xraylib#77]
In XOP, the "Crystal.dat" file in "my XOP directory\data\dabax" can be editted. Then I can change the lattice constant of the crystals.
I failed to figure out a way to edit the structure in OASYS. 
Would you please suggest how to edit or add crystal structures in the crystal list for OASYS-XOPPY, or SHADOW?
Thanks,

**Comment by tschoonj** [comment]
Hi,

Currently the python bindings do not support adding new crystals to the internal array. I will look into fixing this for the next release. However, even then, OASYS itself will need to be modified to take advantage of this feature.

I will keep this ticket open until things have been fixed on the xraylib side of things...

Many thanks for reporting this.

Tom

**Comment by tschoonj** [comment]
xraylib has now support for adding crystals to the internal array from python.

However, for this to work in XOPPY or SHADOW, @srio or @lucarebuffi will need to add support for it though...
