### ISSUE TITLE
Can import xraylib_np, but not xraylib

### ISSUE THREAD

**Issue by toww1g15** [tschoonj/xraylib#90]
Hi,
I'm following the compilation from source instructions on the wiki, but I keep running into a problem- while I'm able to import the xraylib_np module, I cannot import xraylib, getting an ```ImportError: No module named xraylib``` error.

Regarding the install, I've tried a combination of ./configure and ./configure --enable-python-integration, and sudo make check always reports 3 passes on 3 checks.

Perhaps important to note: To begin with, on importing xraylib_np I would also get a  ```ImportError: libxrl.so.7: cannot open shared object file: No such file or directory ``` error. I fixed this by adding a .conf file in  ```/etc/ld.so.conf.d/ ``` that contained the path to the directory that contained libxrl.so.7 (/usr/local/lib)

I'm using Linux Mint 18.3 Cinnamon 64-bit, using the Linux 4.10.0-38-generic Kernel. As an aside, do you know if this is compatible with any of the packages you've compiled for Ubuntu? apt-get would be a lifesaver!

Apologies if this issue has a fairly trivial solution; I don't have a massive amount of experience with Linux systems. Thanks,

Toby

**Comment by toww1g15** [comment]
Hey Tom,
Thanks for getting back to me so quickly, installing swig and re-running configure, make and make install did the trick

Best,
Toby

**Comment by tschoonj** [comment]
Ok, glad to read you got it working.

Best,

Tom
